from app.core.config.settings import settings

# Rate limit strings for easy reuse
RATE_LIMIT_GLOBAL_MINUTE = f"{settings.RATE_LIMIT_PER_MINUTE}/minute"
RATE_LIMIT_GLOBAL_HOUR = f"{settings.RATE_LIMIT_PER_HOUR}/hour"

RATE_LIMIT_AUTH_MINUTE = f"{settings.RATE_LIMIT_AUTH_PER_MINUTE}/minute"
RATE_LIMIT_AUTH_HOUR = f"{settings.RATE_LIMIT_AUTH_PER_HOUR}/hour"

RATE_LIMIT_CONVERSATION_START_MINUTE = f"{settings.RATE_LIMIT_CONVERSATION_START_PER_MINUTE}/minute"
RATE_LIMIT_CONVERSATION_START_HOUR = f"{settings.RATE_LIMIT_CONVERSATION_START_PER_HOUR}/hour"

RATE_LIMIT_CONVERSATION_UPDATE_MINUTE = f"{settings.RATE_LIMIT_CONVERSATION_UPDATE_PER_MINUTE}/minute"
RATE_LIMIT_CONVERSATION_UPDATE_HOUR = f"{settings.RATE_LIMIT_CONVERSATION_UPDATE_PER_HOUR}/hour"
